version: "3"

services:
        nginx:
                build: requirements/nginx/
                image: nginx
                container_name: nginx
                ports: [443:443]
                restart: always
                volumes: [wordpress:/var/www/]
                depends_on: [wordpress]
                networks: [odomenic-net]
        mariadb:
                build: 
                        context: requirements/mariadb/
                        args:
                                - DB_NAME
                                - DB_USER
                                - DB_PASSWORD
                                - ROOT_PASSWORD
                image: mariadb
                container_name: mariadb
                restart: always
                volumes: [mariadb:/var/mylib/mysql/]
                env_file: [.env]
                networks: [odomenic-net]
        wordpress:
                build: requirements/wordpress/
                image: wordpress
                container_name: wordpress
                restart: always
                volumes: [wordpress:/var/www/]
                depends_on: [mariadb]
                env_file: [.env]
                networks: [odomenic-net]
        site:
                build: requirements/bonus/site/
                image: site
                container_name: site
                restart: always
                volumes: [site:/var/www/]
                networks: [odomenic-net]
        adminer:
                build: requirements/bonus/adminer/
                image: adminer
                container_name: adminer
                restart: always
                volumes: [wordpress:/var/www/html/]
                depends_on: [wordpress]
                networks: [odomenic-net]


volumes:
        wordpress: {name: wordpress, driver: local, driver_opts: {type: none, o: bind, device: /home/odomenic/data/wordpress}}
        mariadb: {name: mariadb, driver: local, driver_opts: {type: none, o: bind, device: /home/odomenic/data/mariadb}}
        site: {name: site, driver: local, driver_opts: {type: none, o: bind, device: /home/odomenic/data/site}}

networks:
        odomenic-net:
                driver: bridge
