version: "3"

services:
	nginx:
		build: requirements/nginx/
		image: nginx
		ports: [443:443]
		restart: always
		depends_on: [wordpress]
		volume: [wordpress]
		networks: [odomenic-net]
	
	wordpress:
    	build: requirements/wordpress/
		image: wordpress
		restart: always #or on-failure
		depends_on: [mariadb]
		env_file: [.env]
		volume: [wordpress]
		networks: [odomenic-net]

  mariadb:
		build: requirements/mariadb/
    	image: mariadb
		restart: always
		env_file: [.env]
		volume: [mariadb]
		networks: [odomenic-net]
	
	site: # to install my html page


volumes:
	mariadb:
		driver: local

	wordpress:
		driver: local

"/home/odomenic/data"

network: 
	odomenic-net:
		driver: bridge
